server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: interview_service
  datasource:
    url: jdbc:mysql://localhost:3306/questions?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: life
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
wechat:
  url: https://api.weixin.qq.com/sns/jscode2session
  appId: wxd5cf88ab5fbc0019
  appSecret: b71fc38ea198d26f7a71f00d51b9d6c8
